# Generated by Django 4.2.7 on 2023-12-05 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SaulCastECom', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='podcast',
            name='thumbnail_url',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='podcast',
            name='length',
            field=models.IntegerField(),
        ),
    ]
